### ISSUE TITLE
Actividad 2, Hernández Matra Jorge Luis grupo:1BS

### ISSUE THREAD

**Issue by JORGELUIS2266** [SistemasTecTlaxiaco/actividad-2-infografia-JORGELUIS2266#1]
[Hernández Matra Jorge Luis - infografía.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-infografia-JORGELUIS2266/files/9470074/Hernandez.Matra.Jorge.Luis.-.infografia.pdf)

**Comment by josealfredo79** [comment]
Faltan elementos ...

**Comment by josealfredo79** [comment]
Calificación 16
